#!/bin/bash
#

#    agile - Agile management tool
#    Copyright (C) 2018 adisezhm@gmail.com
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

init()
{
	sql=sqlite3
	agileDb=agile.db

	idTbl=id
	pTbl=project
	sTbl=sprint
	wiTbl=workitem

	return 0;
}

#  do common initialization, before below source commands
init "$@"

#  source scripts
source generic.agile
source schema.agile
source i.agile
source d.agile
source q.agile
source u.agile
source r.agile

#  run the given command
"$@"
